const supportedLanguages = ["es", "gl", "en", "fr", "pt", "de", "ca", "eu"];

const translations = {
  es: {
    meta: {
      indexTitle: "Rubricando para Moodle",
      indexDescription: "Rubricando para Moodle es una extensión que importa rúbricas de Moodle desde archivos CSV/Excel.",
      privacyTitle: "Política de Privacidad | Rubricando para Moodle",
      privacyDescription: "Política de privacidad de Rubricando para Moodle."
    },
    language: { label: "Idioma" },
    nav: {
      main: "Navegación principal",
      homeLabel: "Inicio de Rubricando para Moodle",
      sections: "Secciones de la página",
      privacyNav: "Navegación de privacidad",
      workflow: "Flujo",
      format: "Formato CSV/Excel",
      prompt: "Prompt IA",
      install: "Instalación",
      privacy: "Privacidad",
      home: "Inicio"
    },
    footer: {
      privacy: "Política de privacidad",
      backHome: "Volver a la portada"
    },
    index: {
      heroEyebrow: "Importación CSV/Excel para el editor de rúbricas de Moodle",
      heroTitle: "Crea rúbricas de Moodle desde un CSV/Excel en lugar de rellenar cada celda a mano.",
      heroText: "Rubricando para Moodle añade una capa de importación ligera sobre el editor de rúbricas de Moodle. Suelta un CSV/Excel, revisa la estructura y deja que la extensión complete criterios, descripciones de nivel y puntuaciones directamente en la página que ya usas.",
      installCta: "Instalar desde Chrome Web Store",
      formatCta: "Ver formato CSV/Excel",
      heroPointsLabel: "Ventajas principales",
      pointOne: "Funciona directamente dentro de las páginas de edición de rúbricas de Moodle",
      pointTwo: "Acepta archivos CSV/Excel simples con dos filas por criterio",
      pointThree: "Mantiene la extensión ligera con un parser CSV nativo",
      heroImageAlt: "Zona de importación de Rubricando dentro de una página de edición de rúbricas de Moodle",
      workflowTitle: "Así funciona",
      workflowText: "Hay dos momentos clave: importar el CSV/Excel y terminar con una rúbrica ya estructurada dentro de Moodle.",
      stepOneTitle: "Suelta el CSV/Excel sobre el editor de rúbricas",
      stepOneText: "La extensión inserta una zona de importación visible en las URLs compatibles del editor de rúbricas de Moodle, así que la importación empieza exactamente donde se está editando la rúbrica.",
      stepOneAlt: "Interfaz de importación CSV/Excel insertada en el editor de rúbricas de Moodle",
      stepTwoTitle: "Rellena criterios, niveles y puntuaciones",
      stepTwoText: "Una vez interpretado el archivo, Rubricando completa el formulario de la rúbrica con la estructura importada y muestra un mensaje de confirmación directamente en la página.",
      stepTwoAlt: "Contenido de la rúbrica importado en Moodle con confirmación de éxito",
      formatTitle: "Cómo debe estructurarse el CSV/Excel",
      formatText: "El formato es deliberadamente simple. Cada criterio ocupa dos filas y crece hacia la derecha.",
      rulesTitle: "Reglas",
      ruleOne: "La columna <code>A</code> contiene el nombre del criterio.",
      ruleTwo: "Cada criterio usa exactamente dos filas.",
      ruleThree: "Desde la columna <code>B</code> en adelante van las descripciones de nivel en la primera fila.",
      ruleFour: "La fila inferior contiene la puntuación numérica de cada nivel.",
      ruleFive: "La importación se detiene al encontrar una celda vacía de criterio en la columna <code>A</code>.",
      csvTitle: "Ejemplo CSV",
      csvExample: "Claridad,Insuficiente,Adecuado,Excelente\n,1,3,5\nArgumentación,Débil,Correcta,Sólida\n,2,4,6",
      mapTitle: "Mapa visual",
      mapLabel: "Ejemplo de estructura CSV por columnas",
      mapCriterion: "Criterio",
      mapLevelText: "Texto nivel",
      mapPoints: "Puntos",
      promptTitle: "Genera rúbricas con IA en el formato correcto",
      promptText: "Puedes pedir a una IA que prepare la rúbrica directamente como CSV compatible con Rubricando. Ajusta la actividad, el nivel educativo, los criterios y las puntuaciones antes de usarlo.",
      promptCardTitle: "Prompt recomendado",
      promptExample: "Actúa como especialista en evaluación educativa.\nCrea una rúbrica para: [actividad].\nNivel educativo: [nivel].\nNúmero de criterios: [número].\nNiveles de desempeño: [nombres de niveles y puntuaciones].\n\nDevuelve únicamente CSV válido, sin Markdown, sin encabezados y sin explicación.\nFormato obligatorio:\n- Cada criterio ocupa dos filas.\n- En la primera fila, columna A: nombre del criterio; columnas B en adelante: descripciones de nivel.\n- En la segunda fila, columna A vacía; columnas B en adelante: puntuaciones numéricas.\n- Usa coma como separador.\n- Si algún texto contiene comas, encierra esa celda entre comillas dobles.",
      promptNoteTitle: "Antes de importar",
      promptNoteText: "Revisa el CSV en una hoja de cálculo antes de importarlo. La extensión espera dos filas por criterio: una con descripciones y otra con puntuaciones.",
      featuresTitle: "Por qué se usa",
      featuresText: "Está diseñada con foco: una sola tarea, resuelta directamente dentro del flujo de Moodle.",
      featureOneTitle: "Preparación rápida",
      featureOneText: "Prepara la estructura de la rúbrica en un CSV/Excel y evita reconstruir cada nivel manualmente dentro de Moodle.",
      featureTwoTitle: "Huella ligera",
      featureTwoText: "No incluye librerías de hojas de cálculo de terceros, lo que mantiene el paquete pequeño y directo.",
      featureThreeTitle: "Interfaz localizada",
      featureThreeText: "Incluye inglés, español, francés, alemán, portugués, gallego, catalán y euskera.",
      installTitle: "Lista para instalar",
      installText: "La versión {version} se instala desde Chrome Web Store.",
      storeCta: "Abrir en Chrome Web Store"
    },
    privacy: {
      heroTitle: "Política de Privacidad",
      heroText: "Esta Política de Privacidad explica cómo Rubricando para Moodle trata los datos cuando los usuarios importan rúbricas de Moodle desde archivos CSV/Excel y, cuando existan, utilizan funciones asistidas por IA.",
      whoTitle: "Quiénes somos",
      whoText: "Rubricando para Moodle es una extensión de Chrome diseñada para ayudar a importar criterios, descripciones de nivel y puntuaciones a páginas de edición de rúbricas de Moodle desde archivos CSV/Excel.",
      dataTitle: "Qué datos trata la extensión",
      dataIntro: "La extensión puede tratar las siguientes categorías de datos:",
      dataOne: "Archivos CSV/Excel seleccionados o soltados explícitamente por el usuario.",
      dataTwo: "Contenido relacionado con rúbricas ya presente en páginas compatibles de edición de rúbricas de Moodle.",
      dataThree: "Acciones del usuario necesarias para realizar la importación, como seleccionar un archivo o iniciarla.",
      dataFour: "Datos técnicos de solicitud necesarios para completar llamadas opcionales a APIs remotas de IA, si esas funciones están habilitadas.",
      useTitle: "Cómo usa la extensión los datos",
      useOne: "Para interpretar el contenido CSV/Excel y extraer criterios, niveles y puntuaciones.",
      useTwo: "Para insertar la interfaz de importación en páginas compatibles de edición de rúbricas de Moodle.",
      useThree: "Para completar el formulario de la rúbrica de Moodle con los datos proporcionados por el usuario.",
      useFour: "Para dar soporte a funciones opcionales asistidas por IA, si existen y el usuario las utiliza.",
      aiTitle: "Procesamiento con IA",
      aiText: "La extensión puede incluir funciones asistidas por IA en algunas versiones. Cuando esas funciones estén disponibles, los datos podrán procesarse de una de estas dos formas, según la función y la configuración:",
      aiOne: "Localmente en el dispositivo del usuario mediante un modelo en local.",
      aiTwo: "De forma remota a través de un proveedor externo de API de IA utilizado para completar la función solicitada.",
      aiProviderText: "Cuando se utilice procesamiento remoto con IA, solo debería transmitirse el contenido razonablemente necesario para ejecutar la función solicitada por el usuario. Esto puede incluir fragmentos del archivo CSV/Excel seleccionado, texto de la rúbrica en la página de Moodle y prompts o instrucciones del usuario. Si se usa un proveedor remoto, ese proveedor podrá tratar los datos enviados conforme a sus propios términos y política de privacidad.",
      shareTitle: "Compartición de datos",
      shareText: "No vendemos datos de usuario. No compartimos datos de usuario con terceros salvo en estos casos:",
      shareOne: "Cuando el usuario utiliza explícitamente una función asistida por IA que depende de un proveedor remoto de API.",
      shareTwo: "Cuando la divulgación es exigida por ley, regulación o proceso legal.",
      shareThree: "Cuando compartir la información es técnicamente necesario para prestar la función solicitada a través de la infraestructura de red.",
      remoteTitle: "Código remoto",
      remoteText: "La extensión no descarga ni ejecuta código remoto JavaScript o WebAssembly como parte de su funcionamiento principal.",
      retentionTitle: "Conservación de datos",
      retentionText: "La extensión está diseñada para procesar las importaciones localmente en el navegador siempre que sea posible. No operamos una base de datos backend para almacenar archivos de rúbricas importados ni contenido de páginas Moodle. Si se utiliza una API remota opcional de IA, los datos transmitidos podrán ser conservados por el proveedor correspondiente según su propia política.",
      securityTitle: "Seguridad",
      securityText: "Procuramos minimizar el acceso a datos a lo estrictamente necesario para la finalidad única de la extensión. Cuando existan solicitudes a APIs remotas, deberían transmitirse por canales seguros como HTTPS.",
      choiceTitle: "Opciones del usuario",
      choiceOne: "Los usuarios eligen qué archivo CSV/Excel importar.",
      choiceTwo: "Los usuarios pueden dejar de usar la extensión en cualquier momento desinstalándola.",
      choiceThree: "Los usuarios pueden evitar el procesamiento remoto con IA no utilizando funciones asistidas por IA que dependan de APIs externas.",
      changesTitle: "Cambios en esta política",
      changesText: "Esta Política de Privacidad puede actualizarse cuando cambie la extensión, incluyendo el caso de que se introduzcan nuevas funciones asistidas por IA o nuevas integraciones. La última versión publicada de esta página es la que resulta aplicable.",
      contactTitle: "Contacto",
      contactText: "Para consultas de privacidad o soporte, utiliza el contacto o la URL de soporte indicada en la ficha de Chrome Web Store de Rubricando para Moodle."
    }
  },
  gl: {
    meta: {
      indexTitle: "Rubricando para Moodle",
      indexDescription: "Rubricando para Moodle é unha extensión que importa rúbricas de Moodle desde ficheiros CSV/Excel.",
      privacyTitle: "Política de Privacidade | Rubricando para Moodle",
      privacyDescription: "Política de privacidade de Rubricando para Moodle."
    },
    language: { label: "Idioma" },
    nav: {
      main: "Navegación principal",
      homeLabel: "Inicio de Rubricando para Moodle",
      sections: "Seccións da páxina",
      privacyNav: "Navegación de privacidade",
      workflow: "Fluxo",
      format: "Formato CSV/Excel",
      prompt: "Prompt IA",
      install: "Instalación",
      privacy: "Privacidade",
      home: "Inicio"
    },
    footer: {
      privacy: "Política de privacidade",
      backHome: "Volver á portada"
    },
    index: {
      heroEyebrow: "Importación CSV/Excel para o editor de rúbricas de Moodle",
      heroTitle: "Crea rúbricas de Moodle desde un CSV/Excel en vez de cubrir cada cela á man.",
      heroText: "Rubricando para Moodle engade unha capa lixeira de importación sobre o editor de rúbricas de Moodle. Solta un CSV/Excel, revisa a estrutura e deixa que a extensión complete criterios, descricións de nivel e puntuacións directamente na páxina que xa usas.",
      installCta: "Instalar desde Chrome Web Store",
      formatCta: "Ver formato CSV/Excel",
      heroPointsLabel: "Vantaxes principais",
      pointOne: "Funciona directamente dentro das páxinas de edición de rúbricas de Moodle",
      pointTwo: "Acepta ficheiros CSV/Excel simples con dúas filas por criterio",
      pointThree: "Mantén a extensión lixeira cun parser CSV nativo",
      heroImageAlt: "Zona de importación de Rubricando dentro dunha páxina de edición de rúbricas de Moodle",
      workflowTitle: "Así funciona",
      workflowText: "Hai dous momentos clave: importar o CSV/Excel e rematar cunha rúbrica xa estruturada dentro de Moodle.",
      stepOneTitle: "Solta o CSV/Excel sobre o editor de rúbricas",
      stepOneText: "A extensión insire unha zona de importación visible nos URL compatibles do editor de rúbricas de Moodle, así que a importación comeza exactamente onde se está editando a rúbrica.",
      stepOneAlt: "Interface de importación CSV/Excel inserida no editor de rúbricas de Moodle",
      stepTwoTitle: "Cubre criterios, niveis e puntuacións",
      stepTwoText: "Unha vez interpretado o ficheiro, Rubricando completa o formulario da rúbrica coa estrutura importada e mostra unha mensaxe de confirmación directamente na páxina.",
      stepTwoAlt: "Contido da rúbrica importado en Moodle con confirmación de éxito",
      formatTitle: "Como debe estruturarse o CSV/Excel",
      formatText: "O formato é deliberadamente simple. Cada criterio ocupa dúas filas e medra cara á dereita.",
      rulesTitle: "Regras",
      ruleOne: "A columna <code>A</code> contén o nome do criterio.",
      ruleTwo: "Cada criterio usa exactamente dúas filas.",
      ruleThree: "Desde a columna <code>B</code> en diante van as descricións de nivel na primeira fila.",
      ruleFour: "A fila inferior contén a puntuación numérica de cada nivel.",
      ruleFive: "A importación detense ao atopar unha cela baleira de criterio na columna <code>A</code>.",
      csvTitle: "Exemplo CSV",
      csvExample: "Claridade,Insuficiente,Adecuado,Excelente\n,1,3,5\nArgumentación,Débil,Correcta,Sólida\n,2,4,6",
      mapTitle: "Mapa visual",
      mapLabel: "Exemplo de estrutura CSV por columnas",
      mapCriterion: "Criterio",
      mapLevelText: "Texto nivel",
      mapPoints: "Puntos",
      promptTitle: "Xera rúbricas con IA no formato correcto",
      promptText: "Podes pedir a unha IA que prepare a rúbrica directamente como CSV compatible con Rubricando. Axusta a actividade, o nivel educativo, os criterios e as puntuacións antes de usalo.",
      promptCardTitle: "Prompt recomendado",
      promptExample: "Actúa como especialista en avaliación educativa.\nCrea unha rúbrica para: [actividade].\nNivel educativo: [nivel].\nNúmero de criterios: [número].\nNiveis de desempeño: [nomes de niveis e puntuacións].\n\nDevolve unicamente CSV válido, sen Markdown, sen cabeceiras e sen explicación.\nFormato obrigatorio:\n- Cada criterio ocupa dúas filas.\n- Na primeira fila, columna A: nome do criterio; columnas B en diante: descricións de nivel.\n- Na segunda fila, columna A baleira; columnas B en diante: puntuacións numéricas.\n- Usa coma como separador.\n- Se algún texto contén comas, encerra esa cela entre comiñas dobres.",
      promptNoteTitle: "Antes de importar",
      promptNoteText: "Revisa o CSV nunha folla de cálculo antes de importalo. A extensión espera dúas filas por criterio: unha con descricións e outra con puntuacións.",
      featuresTitle: "Por que se usa",
      featuresText: "Está deseñada con foco: unha soa tarefa, resolta directamente dentro do fluxo de Moodle.",
      featureOneTitle: "Preparación rápida",
      featureOneText: "Prepara a estrutura da rúbrica nun CSV/Excel e evita reconstruír cada nivel manualmente dentro de Moodle.",
      featureTwoTitle: "Pegada lixeira",
      featureTwoText: "Non inclúe librarías de follas de cálculo de terceiros, o que mantén o paquete pequeno e directo.",
      featureThreeTitle: "Interface localizada",
      featureThreeText: "Inclúe inglés, español, francés, alemán, portugués, galego, catalán e éuscaro.",
      installTitle: "Lista para instalar",
      installText: "A versión {version} instálase desde Chrome Web Store.",
      storeCta: "Abrir en Chrome Web Store"
    },
    privacy: {
      heroTitle: "Política de Privacidade",
      heroText: "Esta Política de Privacidade explica como Rubricando para Moodle trata os datos cando os usuarios importan rúbricas de Moodle desde ficheiros CSV/Excel e, cando existan, utilizan funcións asistidas por IA.",
      whoTitle: "Quen somos",
      whoText: "Rubricando para Moodle é unha extensión de Chrome deseñada para axudar a importar criterios, descricións de nivel e puntuacións a páxinas de edición de rúbricas de Moodle desde ficheiros CSV/Excel.",
      dataTitle: "Que datos trata a extensión",
      dataIntro: "A extensión pode tratar as seguintes categorías de datos:",
      dataOne: "Ficheiros CSV/Excel seleccionados ou soltados explicitamente polo usuario.",
      dataTwo: "Contido relacionado con rúbricas xa presente en páxinas compatibles de edición de rúbricas de Moodle.",
      dataThree: "Accións do usuario necesarias para realizar a importación, como seleccionar un ficheiro ou iniciala.",
      dataFour: "Datos técnicos de solicitude necesarios para completar chamadas opcionais a APIs remotas de IA, se esas funcións están habilitadas.",
      useTitle: "Como usa a extensión os datos",
      useOne: "Para interpretar o contido CSV/Excel e extraer criterios, niveis e puntuacións.",
      useTwo: "Para inserir a interface de importación en páxinas compatibles de edición de rúbricas de Moodle.",
      useThree: "Para completar o formulario da rúbrica de Moodle cos datos proporcionados polo usuario.",
      useFour: "Para dar soporte a funcións opcionais asistidas por IA, se existen e o usuario as utiliza.",
      aiTitle: "Procesamento con IA",
      aiText: "A extensión pode incluír funcións asistidas por IA nalgunhas versións. Cando esas funcións estean dispoñibles, os datos poderán procesarse dunha destas dúas formas, segundo a función e a configuración:",
      aiOne: "Localmente no dispositivo do usuario mediante un modelo local.",
      aiTwo: "De forma remota a través dun provedor externo de API de IA utilizado para completar a función solicitada.",
      aiProviderText: "Cando se utilice procesamento remoto con IA, só debería transmitirse o contido razoablemente necesario para executar a función solicitada polo usuario. Isto pode incluír fragmentos do ficheiro CSV/Excel seleccionado, texto da rúbrica na páxina de Moodle e prompts ou instrucións do usuario. Se se usa un provedor remoto, ese provedor poderá tratar os datos enviados conforme aos seus propios termos e política de privacidade.",
      shareTitle: "Compartición de datos",
      shareText: "Non vendemos datos de usuario. Non compartimos datos de usuario con terceiros salvo nestes casos:",
      shareOne: "Cando o usuario utiliza explicitamente unha función asistida por IA que depende dun provedor remoto de API.",
      shareTwo: "Cando a divulgación é esixida por lei, regulación ou proceso legal.",
      shareThree: "Cando compartir a información é tecnicamente necesario para prestar a función solicitada a través da infraestrutura de rede.",
      remoteTitle: "Código remoto",
      remoteText: "A extensión non descarga nin executa código remoto JavaScript ou WebAssembly como parte do seu funcionamento principal.",
      retentionTitle: "Conservación de datos",
      retentionText: "A extensión está deseñada para procesar as importacións localmente no navegador sempre que sexa posible. Non operamos unha base de datos backend para almacenar ficheiros de rúbricas importados nin contido de páxinas Moodle. Se se utiliza unha API remota opcional de IA, os datos transmitidos poderán ser conservados polo provedor correspondente segundo a súa propia política.",
      securityTitle: "Seguridade",
      securityText: "Procuramos minimizar o acceso a datos ao estritamente necesario para a finalidade única da extensión. Cando existan solicitudes a APIs remotas, deberían transmitirse por canles seguras como HTTPS.",
      choiceTitle: "Opcións do usuario",
      choiceOne: "Os usuarios elixen que ficheiro CSV/Excel importar.",
      choiceTwo: "Os usuarios poden deixar de usar a extensión en calquera momento desinstalándoa.",
      choiceThree: "Os usuarios poden evitar o procesamento remoto con IA non utilizando funcións asistidas por IA que dependan de APIs externas.",
      changesTitle: "Cambios nesta política",
      changesText: "Esta Política de Privacidade pode actualizarse cando cambie a extensión, incluíndo o caso de que se introduzan novas funcións asistidas por IA ou novas integracións. A última versión publicada desta páxina é a que resulta aplicable.",
      contactTitle: "Contacto",
      contactText: "Para consultas de privacidade ou soporte, utiliza o contacto ou o URL de soporte indicado na ficha de Chrome Web Store de Rubricando para Moodle."
    }
  },
  en: {
    meta: {
      indexTitle: "Rubricando for Moodle",
      indexDescription: "Rubricando for Moodle is an extension that imports Moodle rubrics from CSV/Excel files.",
      privacyTitle: "Privacy Policy | Rubricando for Moodle",
      privacyDescription: "Privacy policy for Rubricando for Moodle."
    },
    language: { label: "Language" },
    nav: {
      main: "Main navigation",
      homeLabel: "Rubricando for Moodle home",
      sections: "Page sections",
      privacyNav: "Privacy navigation",
      workflow: "Workflow",
      format: "CSV/Excel format",
      prompt: "AI prompt",
      install: "Install",
      privacy: "Privacy",
      home: "Home"
    },
    footer: {
      privacy: "Privacy policy",
      backHome: "Back to home"
    },
    index: {
      heroEyebrow: "CSV/Excel import for Moodle's rubric editor",
      heroTitle: "Create Moodle rubrics from a CSV/Excel instead of filling every cell by hand.",
      heroText: "Rubricando for Moodle adds a lightweight import layer on top of Moodle's rubric editor. Drop a CSV/Excel, review the structure and let the extension complete criteria, level descriptions and scores directly on the page you already use.",
      installCta: "Install from Chrome Web Store",
      formatCta: "View CSV/Excel format",
      heroPointsLabel: "Main benefits",
      pointOne: "Works directly inside Moodle rubric editing pages",
      pointTwo: "Accepts simple CSV/Excel files with two rows per criterion",
      pointThree: "Keeps the extension lightweight with a native CSV parser",
      heroImageAlt: "Rubricando import area inside a Moodle rubric editing page",
      workflowTitle: "How it works",
      workflowText: "There are two key moments: import the CSV/Excel and finish with a structured rubric inside Moodle.",
      stepOneTitle: "Drop the CSV/Excel onto the rubric editor",
      stepOneText: "The extension inserts a visible import area on compatible Moodle rubric editor URLs, so the import starts exactly where the rubric is being edited.",
      stepOneAlt: "CSV/Excel import interface inserted into Moodle's rubric editor",
      stepTwoTitle: "Fill criteria, levels and scores",
      stepTwoText: "After reading the file, Rubricando completes the rubric form with the imported structure and shows a confirmation message directly on the page.",
      stepTwoAlt: "Rubric content imported into Moodle with a success confirmation",
      formatTitle: "How the CSV/Excel must be structured",
      formatText: "The format is deliberately simple. Each criterion uses two rows and grows to the right.",
      rulesTitle: "Rules",
      ruleOne: "Column <code>A</code> contains the criterion name.",
      ruleTwo: "Each criterion uses exactly two rows.",
      ruleThree: "From column <code>B</code> onward, level descriptions go in the first row.",
      ruleFour: "The lower row contains the numeric score for each level.",
      ruleFive: "Import stops when an empty criterion cell is found in column <code>A</code>.",
      csvTitle: "CSV example",
      csvExample: "Clarity,Insufficient,Adequate,Excellent\n,1,3,5\nArgumentation,Weak,Correct,Solid\n,2,4,6",
      mapTitle: "Visual map",
      mapLabel: "Example CSV structure by columns",
      mapCriterion: "Criterion",
      mapLevelText: "Level text",
      mapPoints: "Points",
      promptTitle: "Generate rubrics with AI in the right format",
      promptText: "You can ask an AI tool to prepare the rubric directly as a CSV compatible with Rubricando. Adjust the activity, education level, criteria and scores before using it.",
      promptCardTitle: "Recommended prompt",
      promptExample: "Act as an educational assessment specialist.\nCreate a rubric for: [activity].\nEducation level: [level].\nNumber of criteria: [number].\nPerformance levels: [level names and scores].\n\nReturn only valid CSV, with no Markdown, no headers and no explanation.\nRequired format:\n- Each criterion uses two rows.\n- In the first row, column A: criterion name; columns B onward: level descriptions.\n- In the second row, column A empty; columns B onward: numeric scores.\n- Use comma as the separator.\n- If any text contains commas, wrap that cell in double quotes.",
      promptNoteTitle: "Before importing",
      promptNoteText: "Review the CSV in a spreadsheet before importing it. The extension expects two rows per criterion: one with descriptions and one with scores.",
      featuresTitle: "Why it is used",
      featuresText: "It is focused by design: one task, solved directly inside the Moodle workflow.",
      featureOneTitle: "Fast preparation",
      featureOneText: "Prepare the rubric structure in a CSV/Excel and avoid rebuilding each level manually inside Moodle.",
      featureTwoTitle: "Light footprint",
      featureTwoText: "It does not include third-party spreadsheet libraries, keeping the package small and direct.",
      featureThreeTitle: "Localized interface",
      featureThreeText: "Includes English, Spanish, French, German, Portuguese, Galician, Catalan and Basque.",
      installTitle: "Ready to install",
      installText: "Version {version} is installed from Chrome Web Store.",
      storeCta: "Open in Chrome Web Store"
    },
    privacy: {
      heroTitle: "Privacy Policy",
      heroText: "This Privacy Policy explains how Rubricando for Moodle handles data when users import Moodle rubrics from CSV/Excel files and, where available, use AI-assisted features.",
      whoTitle: "Who we are",
      whoText: "Rubricando for Moodle is a Chrome extension designed to help import criteria, level descriptions and scores into Moodle rubric editing pages from CSV/Excel files.",
      dataTitle: "What data the extension handles",
      dataIntro: "The extension may handle the following categories of data:",
      dataOne: "CSV/Excel files explicitly selected or dropped by the user.",
      dataTwo: "Rubric-related content already present on compatible Moodle rubric editing pages.",
      dataThree: "User actions required to perform the import, such as selecting a file or starting it.",
      dataFour: "Technical request data needed to complete optional calls to remote AI APIs, if those features are enabled.",
      useTitle: "How the extension uses data",
      useOne: "To interpret CSV/Excel content and extract criteria, levels and scores.",
      useTwo: "To insert the import interface into compatible Moodle rubric editing pages.",
      useThree: "To complete the Moodle rubric form with the data provided by the user.",
      useFour: "To support optional AI-assisted features, if they exist and the user uses them.",
      aiTitle: "AI processing",
      aiText: "The extension may include AI-assisted features in some versions. When those features are available, data may be processed in one of these two ways, depending on the feature and configuration:",
      aiOne: "Locally on the user's device through a local model.",
      aiTwo: "Remotely through an external AI API provider used to complete the requested feature.",
      aiProviderText: "When remote AI processing is used, only the content reasonably necessary to run the feature requested by the user should be transmitted. This may include parts of the selected CSV/Excel file, rubric text on the Moodle page and user prompts or instructions. If a remote provider is used, that provider may handle the submitted data according to its own terms and privacy policy.",
      shareTitle: "Data sharing",
      shareText: "We do not sell user data. We do not share user data with third parties except in these cases:",
      shareOne: "When the user explicitly uses an AI-assisted feature that depends on a remote API provider.",
      shareTwo: "When disclosure is required by law, regulation or legal process.",
      shareThree: "When sharing information is technically necessary to provide the requested feature through network infrastructure.",
      remoteTitle: "Remote code",
      remoteText: "The extension does not download or execute remote JavaScript or WebAssembly code as part of its main operation.",
      retentionTitle: "Data retention",
      retentionText: "The extension is designed to process imports locally in the browser whenever possible. We do not operate a backend database to store imported rubric files or Moodle page content. If an optional remote AI API is used, transmitted data may be retained by the relevant provider according to its own policy.",
      securityTitle: "Security",
      securityText: "We aim to minimize data access to what is strictly necessary for the extension's single purpose. When requests to remote APIs exist, they should be transmitted through secure channels such as HTTPS.",
      choiceTitle: "User choices",
      choiceOne: "Users choose which CSV/Excel file to import.",
      choiceTwo: "Users can stop using the extension at any time by uninstalling it.",
      choiceThree: "Users can avoid remote AI processing by not using AI-assisted features that depend on external APIs.",
      changesTitle: "Changes to this policy",
      changesText: "This Privacy Policy may be updated when the extension changes, including if new AI-assisted features or integrations are introduced. The latest published version of this page is the applicable version.",
      contactTitle: "Contact",
      contactText: "For privacy or support questions, use the contact or support URL listed in the Chrome Web Store listing for Rubricando for Moodle."
    }
  },
  fr: {
    meta: {
      indexTitle: "Rubricando pour Moodle",
      indexDescription: "Rubricando pour Moodle est une extension qui importe des grilles Moodle depuis des fichiers CSV/Excel.",
      privacyTitle: "Politique de Confidentialité | Rubricando pour Moodle",
      privacyDescription: "Politique de confidentialité de Rubricando pour Moodle."
    },
    language: { label: "Langue" },
    nav: {
      main: "Navigation principale",
      homeLabel: "Accueil de Rubricando pour Moodle",
      sections: "Sections de la page",
      privacyNav: "Navigation de confidentialité",
      workflow: "Flux",
      format: "Format CSV/Excel",
      prompt: "Prompt IA",
      install: "Installation",
      privacy: "Confidentialité",
      home: "Accueil"
    },
    footer: {
      privacy: "Politique de confidentialité",
      backHome: "Retour à l'accueil"
    },
    index: {
      heroEyebrow: "Import CSV/Excel pour l'éditeur de grilles Moodle",
      heroTitle: "Créez des grilles Moodle depuis un CSV/Excel au lieu de remplir chaque cellule à la main.",
      heroText: "Rubricando pour Moodle ajoute une couche d'import légère à l'éditeur de grilles Moodle. Déposez un CSV/Excel, vérifiez la structure et laissez l'extension compléter les critères, les descriptions de niveaux et les scores directement sur la page que vous utilisez déjà.",
      installCta: "Installer depuis Chrome Web Store",
      formatCta: "Voir le format CSV/Excel",
      heroPointsLabel: "Avantages principaux",
      pointOne: "Fonctionne directement dans les pages d'édition de grilles Moodle",
      pointTwo: "Accepte des fichiers CSV/Excel simples avec deux lignes par critère",
      pointThree: "Garde l'extension légère grâce à un parseur CSV natif",
      heroImageAlt: "Zone d'importation de Rubricando dans une page d'édition de grilles Moodle",
      workflowTitle: "Fonctionnement",
      workflowText: "Deux moments comptent: importer le CSV/Excel puis obtenir une grille déjà structurée dans Moodle.",
      stepOneTitle: "Déposez le CSV/Excel sur l'éditeur de grilles",
      stepOneText: "L'extension insère une zone d'importation visible sur les URL compatibles de l'éditeur de grilles Moodle, l'import commence donc exactement là où la grille est éditée.",
      stepOneAlt: "Interface d'import CSV/Excel insérée dans l'éditeur de grilles Moodle",
      stepTwoTitle: "Remplissez critères, niveaux et scores",
      stepTwoText: "Une fois le fichier interprété, Rubricando complète le formulaire de la grille avec la structure importée et affiche un message de confirmation directement sur la page.",
      stepTwoAlt: "Contenu de grille importé dans Moodle avec confirmation de succès",
      formatTitle: "Comment structurer le CSV/Excel",
      formatText: "Le format est volontairement simple. Chaque critère occupe deux lignes et s'étend vers la droite.",
      rulesTitle: "Règles",
      ruleOne: "La colonne <code>A</code> contient le nom du critère.",
      ruleTwo: "Chaque critère utilise exactement deux lignes.",
      ruleThree: "À partir de la colonne <code>B</code>, les descriptions de niveaux vont sur la première ligne.",
      ruleFour: "La ligne inférieure contient le score numérique de chaque niveau.",
      ruleFive: "L'importation s'arrête lorsqu'une cellule de critère vide est trouvée dans la colonne <code>A</code>.",
      csvTitle: "Exemple CSV",
      csvExample: "Clarté,Insuffisant,Adéquat,Excellent\n,1,3,5\nArgumentation,Faible,Correcte,Solide\n,2,4,6",
      mapTitle: "Carte visuelle",
      mapLabel: "Exemple de structure CSV par colonnes",
      mapCriterion: "Critère",
      mapLevelText: "Texte niveau",
      mapPoints: "Points",
      promptTitle: "Générez des grilles avec l'IA au bon format",
      promptText: "Vous pouvez demander à une IA de préparer la grille directement sous forme de CSV compatible avec Rubricando. Ajustez l'activité, le niveau éducatif, les critères et les scores avant de l'utiliser.",
      promptCardTitle: "Prompt recommandé",
      promptExample: "Agis comme un spécialiste de l'évaluation éducative.\nCrée une grille pour: [activité].\nNiveau éducatif: [niveau].\nNombre de critères: [nombre].\nNiveaux de performance: [noms des niveaux et scores].\n\nRetourne uniquement un CSV valide, sans Markdown, sans en-têtes et sans explication.\nFormat obligatoire:\n- Chaque critère occupe deux lignes.\n- Sur la première ligne, colonne A: nom du critère; colonnes B et suivantes: descriptions de niveau.\n- Sur la deuxième ligne, colonne A vide; colonnes B et suivantes: scores numériques.\n- Utilise la virgule comme séparateur.\n- Si un texte contient des virgules, mets cette cellule entre guillemets doubles.",
      promptNoteTitle: "Avant d'importer",
      promptNoteText: "Vérifiez le CSV dans un tableur avant de l'importer. L'extension attend deux lignes par critère: une avec les descriptions et une avec les scores.",
      featuresTitle: "Pourquoi l'utiliser",
      featuresText: "Elle est conçue avec un objectif clair: une seule tâche, résolue directement dans le flux Moodle.",
      featureOneTitle: "Préparation rapide",
      featureOneText: "Préparez la structure de la grille dans un CSV/Excel et évitez de reconstruire chaque niveau manuellement dans Moodle.",
      featureTwoTitle: "Empreinte légère",
      featureTwoText: "Elle n'inclut pas de bibliothèques de tableur tierces, ce qui garde le paquet petit et direct.",
      featureThreeTitle: "Interface localisée",
      featureThreeText: "Inclut l'anglais, l'espagnol, le français, l'allemand, le portugais, le galicien, le catalan et le basque.",
      installTitle: "Prête à installer",
      installText: "La version {version} s'installe depuis Chrome Web Store.",
      storeCta: "Ouvrir dans Chrome Web Store"
    },
    privacy: {
      heroTitle: "Politique de Confidentialité",
      heroText: "Cette Politique de Confidentialité explique comment Rubricando pour Moodle traite les données lorsque les utilisateurs importent des grilles Moodle depuis des fichiers CSV/Excel et, le cas échéant, utilisent des fonctions assistées par IA.",
      whoTitle: "Qui nous sommes",
      whoText: "Rubricando pour Moodle est une extension Chrome conçue pour aider à importer des critères, descriptions de niveaux et scores dans les pages d'édition de grilles Moodle depuis des fichiers CSV/Excel.",
      dataTitle: "Données traitées par l'extension",
      dataIntro: "L'extension peut traiter les catégories de données suivantes:",
      dataOne: "Fichiers CSV/Excel explicitement sélectionnés ou déposés par l'utilisateur.",
      dataTwo: "Contenu lié aux grilles déjà présent dans les pages compatibles d'édition de grilles Moodle.",
      dataThree: "Actions utilisateur nécessaires à l'importation, comme sélectionner un fichier ou la lancer.",
      dataFour: "Données techniques de requête nécessaires aux appels optionnels vers des API d'IA distantes, si ces fonctions sont activées.",
      useTitle: "Utilisation des données par l'extension",
      useOne: "Pour interpréter le contenu CSV/Excel et extraire critères, niveaux et scores.",
      useTwo: "Pour insérer l'interface d'importation dans les pages compatibles d'édition de grilles Moodle.",
      useThree: "Pour compléter le formulaire de grille Moodle avec les données fournies par l'utilisateur.",
      useFour: "Pour prendre en charge les fonctions optionnelles assistées par IA, si elles existent et si l'utilisateur les utilise.",
      aiTitle: "Traitement par IA",
      aiText: "L'extension peut inclure des fonctions assistées par IA dans certaines versions. Lorsque ces fonctions sont disponibles, les données peuvent être traitées de l'une de ces deux façons, selon la fonction et la configuration:",
      aiOne: "Localement sur l'appareil de l'utilisateur au moyen d'un modèle local.",
      aiTwo: "À distance via un fournisseur externe d'API d'IA utilisé pour compléter la fonction demandée.",
      aiProviderText: "Lorsqu'un traitement distant par IA est utilisé, seul le contenu raisonnablement nécessaire pour exécuter la fonction demandée par l'utilisateur devrait être transmis. Cela peut inclure des fragments du fichier CSV/Excel sélectionné, du texte de la grille dans la page Moodle et des prompts ou instructions de l'utilisateur. Si un fournisseur distant est utilisé, celui-ci peut traiter les données envoyées conformément à ses propres conditions et politique de confidentialité.",
      shareTitle: "Partage des données",
      shareText: "Nous ne vendons pas les données utilisateur. Nous ne partageons pas les données utilisateur avec des tiers sauf dans ces cas:",
      shareOne: "Lorsque l'utilisateur utilise explicitement une fonction assistée par IA qui dépend d'un fournisseur d'API distant.",
      shareTwo: "Lorsque la divulgation est exigée par la loi, une réglementation ou une procédure légale.",
      shareThree: "Lorsque le partage de l'information est techniquement nécessaire pour fournir la fonction demandée via l'infrastructure réseau.",
      remoteTitle: "Code distant",
      remoteText: "L'extension ne télécharge ni n'exécute de code JavaScript ou WebAssembly distant dans le cadre de son fonctionnement principal.",
      retentionTitle: "Conservation des données",
      retentionText: "L'extension est conçue pour traiter les importations localement dans le navigateur chaque fois que possible. Nous n'exploitons pas de base de données backend pour stocker des fichiers de grilles importés ou du contenu de pages Moodle. Si une API d'IA distante optionnelle est utilisée, les données transmises peuvent être conservées par le fournisseur concerné selon sa propre politique.",
      securityTitle: "Sécurité",
      securityText: "Nous cherchons à limiter l'accès aux données au strict nécessaire pour l'objectif unique de l'extension. Lorsque des requêtes vers des API distantes existent, elles devraient être transmises par des canaux sécurisés comme HTTPS.",
      choiceTitle: "Choix de l'utilisateur",
      choiceOne: "Les utilisateurs choisissent le fichier CSV/Excel à importer.",
      choiceTwo: "Les utilisateurs peuvent cesser d'utiliser l'extension à tout moment en la désinstallant.",
      choiceThree: "Les utilisateurs peuvent éviter le traitement distant par IA en n'utilisant pas les fonctions assistées par IA qui dépendent d'API externes.",
      changesTitle: "Modifications de cette politique",
      changesText: "Cette Politique de Confidentialité peut être mise à jour lorsque l'extension change, notamment si de nouvelles fonctions assistées par IA ou de nouvelles intégrations sont introduites. La dernière version publiée de cette page est la version applicable.",
      contactTitle: "Contact",
      contactText: "Pour toute question de confidentialité ou de support, utilisez le contact ou l'URL de support indiqués dans la fiche Chrome Web Store de Rubricando pour Moodle."
    }
  },
  pt: {
    meta: {
      indexTitle: "Rubricando para Moodle",
      indexDescription: "Rubricando para Moodle é uma extensão que importa rubricas do Moodle a partir de ficheiros CSV/Excel.",
      privacyTitle: "Política de Privacidade | Rubricando para Moodle",
      privacyDescription: "Política de privacidade do Rubricando para Moodle."
    },
    language: { label: "Idioma" },
    nav: {
      main: "Navegação principal",
      homeLabel: "Início do Rubricando para Moodle",
      sections: "Secções da página",
      privacyNav: "Navegação de privacidade",
      workflow: "Fluxo",
      format: "Formato CSV/Excel",
      prompt: "Prompt IA",
      install: "Instalação",
      privacy: "Privacidade",
      home: "Início"
    },
    footer: {
      privacy: "Política de privacidade",
      backHome: "Voltar à página inicial"
    },
    index: {
      heroEyebrow: "Importação CSV/Excel para o editor de rubricas do Moodle",
      heroTitle: "Crie rubricas do Moodle a partir de um CSV/Excel em vez de preencher cada célula à mão.",
      heroText: "Rubricando para Moodle adiciona uma camada leve de importação ao editor de rubricas do Moodle. Solte um CSV/Excel, reveja a estrutura e deixe a extensão completar critérios, descrições de nível e pontuações diretamente na página que já usa.",
      installCta: "Instalar a partir da Chrome Web Store",
      formatCta: "Ver formato CSV/Excel",
      heroPointsLabel: "Principais vantagens",
      pointOne: "Funciona diretamente nas páginas de edição de rubricas do Moodle",
      pointTwo: "Aceita ficheiros CSV/Excel simples com duas linhas por critério",
      pointThree: "Mantém a extensão leve com um parser CSV nativo",
      heroImageAlt: "Área de importação do Rubricando numa página de edição de rubricas do Moodle",
      workflowTitle: "Como funciona",
      workflowText: "Há dois momentos-chave: importar o CSV/Excel e terminar com uma rubrica já estruturada no Moodle.",
      stepOneTitle: "Solte o CSV/Excel sobre o editor de rubricas",
      stepOneText: "A extensão insere uma área de importação visível nos URLs compatíveis do editor de rubricas do Moodle, para que a importação comece exatamente onde a rubrica está a ser editada.",
      stepOneAlt: "Interface de importação CSV/Excel inserida no editor de rubricas do Moodle",
      stepTwoTitle: "Preencha critérios, níveis e pontuações",
      stepTwoText: "Depois de interpretar o ficheiro, o Rubricando completa o formulário da rubrica com a estrutura importada e mostra uma mensagem de confirmação diretamente na página.",
      stepTwoAlt: "Conteúdo da rubrica importado no Moodle com confirmação de sucesso",
      formatTitle: "Como o CSV/Excel deve ser estruturado",
      formatText: "O formato é deliberadamente simples. Cada critério ocupa duas linhas e cresce para a direita.",
      rulesTitle: "Regras",
      ruleOne: "A coluna <code>A</code> contém o nome do critério.",
      ruleTwo: "Cada critério usa exatamente duas linhas.",
      ruleThree: "A partir da coluna <code>B</code>, as descrições de nível ficam na primeira linha.",
      ruleFour: "A linha inferior contém a pontuação numérica de cada nível.",
      ruleFive: "A importação para quando encontra uma célula de critério vazia na coluna <code>A</code>.",
      csvTitle: "Exemplo CSV",
      csvExample: "Clareza,Insuficiente,Adequado,Excelente\n,1,3,5\nArgumentação,Fraca,Correta,Sólida\n,2,4,6",
      mapTitle: "Mapa visual",
      mapLabel: "Exemplo de estrutura CSV por colunas",
      mapCriterion: "Critério",
      mapLevelText: "Texto nível",
      mapPoints: "Pontos",
      promptTitle: "Gere rubricas com IA no formato correto",
      promptText: "Pode pedir a uma IA que prepare a rubrica diretamente como CSV compatível com o Rubricando. Ajuste a atividade, o nível educativo, os critérios e as pontuações antes de usar.",
      promptCardTitle: "Prompt recomendado",
      promptExample: "Atua como especialista em avaliação educativa.\nCria uma rubrica para: [atividade].\nNível educativo: [nível].\nNúmero de critérios: [número].\nNíveis de desempenho: [nomes dos níveis e pontuações].\n\nDevolve apenas CSV válido, sem Markdown, sem cabeçalhos e sem explicação.\nFormato obrigatório:\n- Cada critério ocupa duas linhas.\n- Na primeira linha, coluna A: nome do critério; colunas B em diante: descrições de nível.\n- Na segunda linha, coluna A vazia; colunas B em diante: pontuações numéricas.\n- Usa vírgula como separador.\n- Se algum texto contiver vírgulas, coloca essa célula entre aspas duplas.",
      promptNoteTitle: "Antes de importar",
      promptNoteText: "Reveja o CSV numa folha de cálculo antes de o importar. A extensão espera duas linhas por critério: uma com descrições e outra com pontuações.",
      featuresTitle: "Porque é usada",
      featuresText: "Foi desenhada com foco: uma única tarefa, resolvida diretamente no fluxo do Moodle.",
      featureOneTitle: "Preparação rápida",
      featureOneText: "Prepare a estrutura da rubrica num CSV/Excel e evite reconstruir cada nível manualmente no Moodle.",
      featureTwoTitle: "Pegada leve",
      featureTwoText: "Não inclui bibliotecas de folhas de cálculo de terceiros, mantendo o pacote pequeno e direto.",
      featureThreeTitle: "Interface localizada",
      featureThreeText: "Inclui inglês, espanhol, francês, alemão, português, galego, catalão e basco.",
      installTitle: "Pronta para instalar",
      installText: "A versão {version} é instalada a partir da Chrome Web Store.",
      storeCta: "Abrir na Chrome Web Store"
    },
    privacy: {
      heroTitle: "Política de Privacidade",
      heroText: "Esta Política de Privacidade explica como o Rubricando para Moodle trata os dados quando os utilizadores importam rubricas do Moodle a partir de ficheiros CSV/Excel e, quando existirem, usam funcionalidades assistidas por IA.",
      whoTitle: "Quem somos",
      whoText: "Rubricando para Moodle é uma extensão do Chrome desenhada para ajudar a importar critérios, descrições de nível e pontuações para páginas de edição de rubricas do Moodle a partir de ficheiros CSV/Excel.",
      dataTitle: "Que dados a extensão trata",
      dataIntro: "A extensão pode tratar as seguintes categorias de dados:",
      dataOne: "Ficheiros CSV/Excel selecionados ou largados explicitamente pelo utilizador.",
      dataTwo: "Conteúdo relacionado com rubricas já presente em páginas compatíveis de edição de rubricas do Moodle.",
      dataThree: "Ações do utilizador necessárias para realizar a importação, como selecionar um ficheiro ou iniciá-la.",
      dataFour: "Dados técnicos de pedido necessários para completar chamadas opcionais a APIs remotas de IA, se essas funcionalidades estiverem ativadas.",
      useTitle: "Como a extensão usa os dados",
      useOne: "Para interpretar o conteúdo CSV/Excel e extrair critérios, níveis e pontuações.",
      useTwo: "Para inserir a interface de importação em páginas compatíveis de edição de rubricas do Moodle.",
      useThree: "Para completar o formulário da rubrica do Moodle com os dados fornecidos pelo utilizador.",
      useFour: "Para dar suporte a funcionalidades opcionais assistidas por IA, se existirem e o utilizador as usar.",
      aiTitle: "Processamento com IA",
      aiText: "A extensão pode incluir funcionalidades assistidas por IA em algumas versões. Quando essas funcionalidades estiverem disponíveis, os dados poderão ser processados de uma destas duas formas, consoante a funcionalidade e a configuração:",
      aiOne: "Localmente no dispositivo do utilizador através de um modelo local.",
      aiTwo: "Remotamente através de um fornecedor externo de API de IA usado para completar a funcionalidade solicitada.",
      aiProviderText: "Quando for usado processamento remoto com IA, só deverá ser transmitido o conteúdo razoavelmente necessário para executar a funcionalidade solicitada pelo utilizador. Isto pode incluir fragmentos do ficheiro CSV/Excel selecionado, texto da rubrica na página Moodle e prompts ou instruções do utilizador. Se for usado um fornecedor remoto, esse fornecedor poderá tratar os dados enviados de acordo com os seus próprios termos e política de privacidade.",
      shareTitle: "Partilha de dados",
      shareText: "Não vendemos dados de utilizador. Não partilhamos dados de utilizador com terceiros exceto nestes casos:",
      shareOne: "Quando o utilizador usa explicitamente uma funcionalidade assistida por IA que depende de um fornecedor remoto de API.",
      shareTwo: "Quando a divulgação é exigida por lei, regulamento ou processo legal.",
      shareThree: "Quando partilhar a informação é tecnicamente necessário para fornecer a funcionalidade solicitada através da infraestrutura de rede.",
      remoteTitle: "Código remoto",
      remoteText: "A extensão não descarrega nem executa código remoto JavaScript ou WebAssembly como parte do seu funcionamento principal.",
      retentionTitle: "Conservação de dados",
      retentionText: "A extensão foi desenhada para processar as importações localmente no navegador sempre que possível. Não operamos uma base de dados backend para armazenar ficheiros de rubricas importados nem conteúdo de páginas Moodle. Se for usada uma API remota opcional de IA, os dados transmitidos poderão ser conservados pelo fornecedor correspondente segundo a sua própria política.",
      securityTitle: "Segurança",
      securityText: "Procuramos minimizar o acesso a dados ao estritamente necessário para a finalidade única da extensão. Quando existirem pedidos a APIs remotas, estes deverão ser transmitidos por canais seguros como HTTPS.",
      choiceTitle: "Opções do utilizador",
      choiceOne: "Os utilizadores escolhem que ficheiro CSV/Excel importar.",
      choiceTwo: "Os utilizadores podem deixar de usar a extensão a qualquer momento desinstalando-a.",
      choiceThree: "Os utilizadores podem evitar o processamento remoto com IA não usando funcionalidades assistidas por IA que dependam de APIs externas.",
      changesTitle: "Alterações a esta política",
      changesText: "Esta Política de Privacidade pode ser atualizada quando a extensão mudar, incluindo caso sejam introduzidas novas funcionalidades assistidas por IA ou novas integrações. A última versão publicada desta página é a versão aplicável.",
      contactTitle: "Contacto",
      contactText: "Para questões de privacidade ou suporte, use o contacto ou o URL de suporte indicado na ficha da Chrome Web Store do Rubricando para Moodle."
    }
  },
  de: {
    meta: {
      indexTitle: "Rubricando für Moodle",
      indexDescription: "Rubricando für Moodle ist eine Erweiterung, die Moodle-Rubriken aus CSV/Excel-Dateien importiert.",
      privacyTitle: "Datenschutzerklärung | Rubricando für Moodle",
      privacyDescription: "Datenschutzerklärung für Rubricando für Moodle."
    },
    language: { label: "Sprache" },
    nav: {
      main: "Hauptnavigation",
      homeLabel: "Startseite von Rubricando für Moodle",
      sections: "Seitenbereiche",
      privacyNav: "Datenschutz-Navigation",
      workflow: "Ablauf",
      format: "CSV/Excel-Format",
      prompt: "KI-Prompt",
      install: "Installation",
      privacy: "Datenschutz",
      home: "Start"
    },
    footer: {
      privacy: "Datenschutzerklärung",
      backHome: "Zurück zur Startseite"
    },
    index: {
      heroEyebrow: "CSV/Excel-Import für den Moodle-Rubrikeditor",
      heroTitle: "Erstellen Sie Moodle-Rubriken aus einer CSV/Excel, statt jede Zelle manuell auszufüllen.",
      heroText: "Rubricando für Moodle ergänzt den Moodle-Rubrikeditor um eine leichte Importschicht. Legen Sie eine CSV/Excel ab, prüfen Sie die Struktur und lassen Sie die Erweiterung Kriterien, Stufenbeschreibungen und Punkte direkt auf der gewohnten Seite ausfüllen.",
      installCta: "Aus dem Chrome Web Store installieren",
      formatCta: "CSV/Excel-Format ansehen",
      heroPointsLabel: "Hauptvorteile",
      pointOne: "Funktioniert direkt in den Bearbeitungsseiten für Moodle-Rubriken",
      pointTwo: "Akzeptiert einfache CSV/Excel-Dateien mit zwei Zeilen pro Kriterium",
      pointThree: "Hält die Erweiterung mit einem nativen CSV-Parser schlank",
      heroImageAlt: "Importbereich von Rubricando in einer Bearbeitungsseite für Moodle-Rubriken",
      workflowTitle: "So funktioniert es",
      workflowText: "Es gibt zwei zentrale Schritte: CSV/Excel importieren und mit einer strukturierten Rubrik in Moodle abschließen.",
      stepOneTitle: "CSV/Excel auf den Rubrikeditor ziehen",
      stepOneText: "Die Erweiterung fügt auf kompatiblen URLs des Moodle-Rubrikeditors einen sichtbaren Importbereich ein, sodass der Import genau dort startet, wo die Rubrik bearbeitet wird.",
      stepOneAlt: "CSV/Excel-Importoberfläche im Moodle-Rubrikeditor",
      stepTwoTitle: "Kriterien, Stufen und Punkte ausfüllen",
      stepTwoText: "Nach dem Lesen der Datei füllt Rubricando das Rubrikformular mit der importierten Struktur aus und zeigt direkt auf der Seite eine Bestätigung.",
      stepTwoAlt: "In Moodle importierter Rubrikinhalt mit Erfolgsbestätigung",
      formatTitle: "So muss die CSV/Excel aufgebaut sein",
      formatText: "Das Format ist bewusst einfach. Jedes Kriterium nutzt zwei Zeilen und wächst nach rechts.",
      rulesTitle: "Regeln",
      ruleOne: "Spalte <code>A</code> enthält den Namen des Kriteriums.",
      ruleTwo: "Jedes Kriterium verwendet genau zwei Zeilen.",
      ruleThree: "Ab Spalte <code>B</code> stehen die Stufenbeschreibungen in der ersten Zeile.",
      ruleFour: "Die untere Zeile enthält die numerische Punktzahl jeder Stufe.",
      ruleFive: "Der Import stoppt, wenn in Spalte <code>A</code> eine leere Kriterienzelle gefunden wird.",
      csvTitle: "CSV-Beispiel",
      csvExample: "Klarheit,Unzureichend,Angemessen,Ausgezeichnet\n,1,3,5\nArgumentation,Schwach,Korrekt,Stark\n,2,4,6",
      mapTitle: "Visuelle Karte",
      mapLabel: "Beispiel einer CSV-Struktur nach Spalten",
      mapCriterion: "Kriterium",
      mapLevelText: "Stufentext",
      mapPoints: "Punkte",
      promptTitle: "Rubriken mit KI im richtigen Format erzeugen",
      promptText: "Sie können ein KI-Tool bitten, die Rubrik direkt als CSV vorzubereiten, die mit Rubricando kompatibel ist. Passen Sie Aktivität, Bildungsstufe, Kriterien und Punktzahlen vor der Nutzung an.",
      promptCardTitle: "Empfohlener Prompt",
      promptExample: "Handle als Spezialist für pädagogische Bewertung.\nErstelle eine Rubrik für: [Aktivität].\nBildungsstufe: [Stufe].\nAnzahl der Kriterien: [Anzahl].\nLeistungsstufen: [Namen der Stufen und Punktzahlen].\n\nGib ausschließlich gültiges CSV zurück, ohne Markdown, ohne Kopfzeilen und ohne Erklärung.\nPflichtformat:\n- Jedes Kriterium nutzt zwei Zeilen.\n- In der ersten Zeile, Spalte A: Name des Kriteriums; Spalten B und folgende: Stufenbeschreibungen.\n- In der zweiten Zeile, Spalte A leer; Spalten B und folgende: numerische Punktzahlen.\n- Verwende Komma als Trennzeichen.\n- Wenn ein Text Kommas enthält, setze diese Zelle in doppelte Anführungszeichen.",
      promptNoteTitle: "Vor dem Import",
      promptNoteText: "Prüfen Sie die CSV vor dem Import in einer Tabellenkalkulation. Die Erweiterung erwartet zwei Zeilen pro Kriterium: eine mit Beschreibungen und eine mit Punktzahlen.",
      featuresTitle: "Warum es genutzt wird",
      featuresText: "Die Erweiterung ist fokussiert: eine Aufgabe, direkt im Moodle-Ablauf gelöst.",
      featureOneTitle: "Schnelle Vorbereitung",
      featureOneText: "Bereiten Sie die Rubrikstruktur in einer CSV/Excel vor und vermeiden Sie es, jede Stufe manuell in Moodle neu aufzubauen.",
      featureTwoTitle: "Schlankes Paket",
      featureTwoText: "Sie enthält keine Drittanbieter-Bibliotheken für Tabellenkalkulationen und bleibt dadurch klein und direkt.",
      featureThreeTitle: "Lokalisierte Oberfläche",
      featureThreeText: "Enthält Englisch, Spanisch, Französisch, Deutsch, Portugiesisch, Galicisch, Katalanisch und Baskisch.",
      installTitle: "Bereit zur Installation",
      installText: "Version {version} wird aus dem Chrome Web Store installiert.",
      storeCta: "Im Chrome Web Store öffnen"
    },
    privacy: {
      heroTitle: "Datenschutzerklärung",
      heroText: "Diese Datenschutzerklärung erläutert, wie Rubricando für Moodle Daten verarbeitet, wenn Nutzer Moodle-Rubriken aus CSV/Excel-Dateien importieren und, sofern verfügbar, KI-gestützte Funktionen verwenden.",
      whoTitle: "Wer wir sind",
      whoText: "Rubricando für Moodle ist eine Chrome-Erweiterung, die Kriterien, Stufenbeschreibungen und Punkte aus CSV/Excel-Dateien in Bearbeitungsseiten für Moodle-Rubriken importiert.",
      dataTitle: "Welche Daten die Erweiterung verarbeitet",
      dataIntro: "Die Erweiterung kann folgende Datenkategorien verarbeiten:",
      dataOne: "CSV/Excel-Dateien, die vom Nutzer ausdrücklich ausgewählt oder abgelegt wurden.",
      dataTwo: "Rubrikbezogene Inhalte, die bereits auf kompatiblen Bearbeitungsseiten für Moodle-Rubriken vorhanden sind.",
      dataThree: "Nutzeraktionen, die für den Import erforderlich sind, etwa das Auswählen oder Starten einer Datei.",
      dataFour: "Technische Anfragedaten, die für optionale Aufrufe entfernter KI-APIs erforderlich sind, sofern diese Funktionen aktiviert sind.",
      useTitle: "Wie die Erweiterung Daten verwendet",
      useOne: "Zum Interpretieren von CSV/Excel-Inhalten und Extrahieren von Kriterien, Stufen und Punkten.",
      useTwo: "Zum Einfügen der Importoberfläche in kompatible Bearbeitungsseiten für Moodle-Rubriken.",
      useThree: "Zum Ausfüllen des Moodle-Rubrikformulars mit den vom Nutzer bereitgestellten Daten.",
      useFour: "Zur Unterstützung optionaler KI-gestützter Funktionen, sofern sie existieren und vom Nutzer verwendet werden.",
      aiTitle: "KI-Verarbeitung",
      aiText: "Die Erweiterung kann in einigen Versionen KI-gestützte Funktionen enthalten. Wenn diese Funktionen verfügbar sind, können Daten je nach Funktion und Konfiguration auf eine dieser zwei Arten verarbeitet werden:",
      aiOne: "Lokal auf dem Gerät des Nutzers durch ein lokales Modell.",
      aiTwo: "Remote über einen externen KI-API-Anbieter, der zur Ausführung der angeforderten Funktion genutzt wird.",
      aiProviderText: "Bei Remote-Verarbeitung durch KI sollte nur der Inhalt übertragen werden, der zur Ausführung der vom Nutzer angeforderten Funktion angemessen erforderlich ist. Dazu können Teile der ausgewählten CSV/Excel-Datei, Rubriktext auf der Moodle-Seite sowie Prompts oder Anweisungen des Nutzers gehören. Wird ein Remote-Anbieter verwendet, kann dieser die übermittelten Daten gemäß seinen eigenen Bedingungen und seiner Datenschutzrichtlinie verarbeiten.",
      shareTitle: "Weitergabe von Daten",
      shareText: "Wir verkaufen keine Nutzerdaten. Wir geben Nutzerdaten nicht an Dritte weiter, außer in diesen Fällen:",
      shareOne: "Wenn der Nutzer ausdrücklich eine KI-gestützte Funktion verwendet, die von einem Remote-API-Anbieter abhängt.",
      shareTwo: "Wenn die Offenlegung durch Gesetz, Vorschrift oder rechtliches Verfahren erforderlich ist.",
      shareThree: "Wenn die Weitergabe der Informationen technisch notwendig ist, um die angeforderte Funktion über die Netzwerkinfrastruktur bereitzustellen.",
      remoteTitle: "Remote-Code",
      remoteText: "Die Erweiterung lädt oder führt im Rahmen ihres Hauptbetriebs keinen entfernten JavaScript- oder WebAssembly-Code aus.",
      retentionTitle: "Datenaufbewahrung",
      retentionText: "Die Erweiterung ist so konzipiert, dass Importe nach Möglichkeit lokal im Browser verarbeitet werden. Wir betreiben keine Backend-Datenbank, um importierte Rubrikdateien oder Inhalte von Moodle-Seiten zu speichern. Wenn eine optionale entfernte KI-API genutzt wird, können übermittelte Daten vom jeweiligen Anbieter gemäß dessen eigener Richtlinie aufbewahrt werden.",
      securityTitle: "Sicherheit",
      securityText: "Wir bemühen uns, den Datenzugriff auf das für den einzigen Zweck der Erweiterung unbedingt Notwendige zu beschränken. Wenn Anfragen an entfernte APIs erfolgen, sollten sie über sichere Kanäle wie HTTPS übertragen werden.",
      choiceTitle: "Nutzeroptionen",
      choiceOne: "Nutzer wählen aus, welche CSV/Excel-Datei importiert wird.",
      choiceTwo: "Nutzer können die Erweiterung jederzeit deinstallieren und nicht mehr verwenden.",
      choiceThree: "Nutzer können Remote-KI-Verarbeitung vermeiden, indem sie keine KI-gestützten Funktionen verwenden, die von externen APIs abhängen.",
      changesTitle: "Änderungen dieser Erklärung",
      changesText: "Diese Datenschutzerklärung kann aktualisiert werden, wenn sich die Erweiterung ändert, etwa wenn neue KI-gestützte Funktionen oder Integrationen eingeführt werden. Es gilt die zuletzt veröffentlichte Version dieser Seite.",
      contactTitle: "Kontakt",
      contactText: "Für Datenschutz- oder Supportfragen verwenden Sie den Kontakt oder die Support-URL im Chrome Web Store-Eintrag von Rubricando für Moodle."
    }
  },
  ca: {
    meta: {
      indexTitle: "Rubricando per a Moodle",
      indexDescription: "Rubricando per a Moodle és una extensió que importa rúbriques de Moodle des de fitxers CSV/Excel.",
      privacyTitle: "Política de Privacitat | Rubricando per a Moodle",
      privacyDescription: "Política de privacitat de Rubricando per a Moodle."
    },
    language: { label: "Idioma" },
    nav: {
      main: "Navegació principal",
      homeLabel: "Inici de Rubricando per a Moodle",
      sections: "Seccions de la pàgina",
      privacyNav: "Navegació de privacitat",
      workflow: "Flux",
      format: "Format CSV/Excel",
      prompt: "Prompt IA",
      install: "Instal·lació",
      privacy: "Privacitat",
      home: "Inici"
    },
    footer: {
      privacy: "Política de privacitat",
      backHome: "Torna a la portada"
    },
    index: {
      heroEyebrow: "Importació CSV/Excel per a l'editor de rúbriques de Moodle",
      heroTitle: "Crea rúbriques de Moodle des d'un CSV/Excel en comptes d'omplir cada cel·la a mà.",
      heroText: "Rubricando per a Moodle afegeix una capa d'importació lleugera sobre l'editor de rúbriques de Moodle. Deixa anar un CSV/Excel, revisa l'estructura i deixa que l'extensió completi criteris, descripcions de nivell i puntuacions directament a la pàgina que ja fas servir.",
      installCta: "Instal·la des de Chrome Web Store",
      formatCta: "Veure format CSV/Excel",
      heroPointsLabel: "Avantatges principals",
      pointOne: "Funciona directament dins de les pàgines d'edició de rúbriques de Moodle",
      pointTwo: "Accepta fitxers CSV/Excel simples amb dues files per criteri",
      pointThree: "Manté l'extensió lleugera amb un parser CSV nadiu",
      heroImageAlt: "Zona d'importació de Rubricando dins d'una pàgina d'edició de rúbriques de Moodle",
      workflowTitle: "Així funciona",
      workflowText: "Hi ha dos moments clau: importar el CSV/Excel i acabar amb una rúbrica ja estructurada dins de Moodle.",
      stepOneTitle: "Deixa anar el CSV/Excel sobre l'editor de rúbriques",
      stepOneText: "L'extensió insereix una zona d'importació visible als URL compatibles de l'editor de rúbriques de Moodle, de manera que la importació comença exactament on s'està editant la rúbrica.",
      stepOneAlt: "Interfície d'importació CSV/Excel inserida a l'editor de rúbriques de Moodle",
      stepTwoTitle: "Omple criteris, nivells i puntuacions",
      stepTwoText: "Un cop interpretat el fitxer, Rubricando completa el formulari de la rúbrica amb l'estructura importada i mostra un missatge de confirmació directament a la pàgina.",
      stepTwoAlt: "Contingut de la rúbrica importat a Moodle amb confirmació d'èxit",
      formatTitle: "Com s'ha d'estructurar el CSV/Excel",
      formatText: "El format és deliberadament simple. Cada criteri ocupa dues files i creix cap a la dreta.",
      rulesTitle: "Regles",
      ruleOne: "La columna <code>A</code> conté el nom del criteri.",
      ruleTwo: "Cada criteri usa exactament dues files.",
      ruleThree: "Des de la columna <code>B</code> endavant hi van les descripcions de nivell a la primera fila.",
      ruleFour: "La fila inferior conté la puntuació numèrica de cada nivell.",
      ruleFive: "La importació s'atura quan troba una cel·la de criteri buida a la columna <code>A</code>.",
      csvTitle: "Exemple CSV",
      csvExample: "Claredat,Insuficient,Adequat,Excel·lent\n,1,3,5\nArgumentació,Dèbil,Correcta,Sòlida\n,2,4,6",
      mapTitle: "Mapa visual",
      mapLabel: "Exemple d'estructura CSV per columnes",
      mapCriterion: "Criteri",
      mapLevelText: "Text nivell",
      mapPoints: "Punts",
      promptTitle: "Genera rúbriques amb IA en el format correcte",
      promptText: "Pots demanar a una IA que prepari la rúbrica directament com a CSV compatible amb Rubricando. Ajusta l'activitat, el nivell educatiu, els criteris i les puntuacions abans d'usar-lo.",
      promptCardTitle: "Prompt recomanat",
      promptExample: "Actua com a especialista en avaluació educativa.\nCrea una rúbrica per a: [activitat].\nNivell educatiu: [nivell].\nNombre de criteris: [nombre].\nNivells d'acompliment: [noms dels nivells i puntuacions].\n\nRetorna únicament CSV vàlid, sense Markdown, sense capçaleres i sense explicació.\nFormat obligatori:\n- Cada criteri ocupa dues files.\n- A la primera fila, columna A: nom del criteri; columnes B en endavant: descripcions de nivell.\n- A la segona fila, columna A buida; columnes B en endavant: puntuacions numèriques.\n- Usa coma com a separador.\n- Si algun text conté comes, posa aquesta cel·la entre cometes dobles.",
      promptNoteTitle: "Abans d'importar",
      promptNoteText: "Revisa el CSV en un full de càlcul abans d'importar-lo. L'extensió espera dues files per criteri: una amb descripcions i una altra amb puntuacions.",
      featuresTitle: "Per què s'utilitza",
      featuresText: "Està dissenyada amb focus: una sola tasca, resolta directament dins del flux de Moodle.",
      featureOneTitle: "Preparació ràpida",
      featureOneText: "Prepara l'estructura de la rúbrica en un CSV/Excel i evita reconstruir cada nivell manualment dins de Moodle.",
      featureTwoTitle: "Empremta lleugera",
      featureTwoText: "No inclou llibreries de fulls de càlcul de tercers, cosa que manté el paquet petit i directe.",
      featureThreeTitle: "Interfície localitzada",
      featureThreeText: "Inclou anglès, espanyol, francès, alemany, portuguès, gallec, català i basc.",
      installTitle: "Llista per instal·lar",
      installText: "La versió {version} s'instal·la des de Chrome Web Store.",
      storeCta: "Obrir a Chrome Web Store"
    },
    privacy: {
      heroTitle: "Política de Privacitat",
      heroText: "Aquesta Política de Privacitat explica com Rubricando per a Moodle tracta les dades quan els usuaris importen rúbriques de Moodle des de fitxers CSV/Excel i, quan existeixin, utilitzen funcions assistides per IA.",
      whoTitle: "Qui som",
      whoText: "Rubricando per a Moodle és una extensió de Chrome dissenyada per ajudar a importar criteris, descripcions de nivell i puntuacions a pàgines d'edició de rúbriques de Moodle des de fitxers CSV/Excel.",
      dataTitle: "Quines dades tracta l'extensió",
      dataIntro: "L'extensió pot tractar les categories de dades següents:",
      dataOne: "Fitxers CSV/Excel seleccionats o deixats anar explícitament per l'usuari.",
      dataTwo: "Contingut relacionat amb rúbriques ja present en pàgines compatibles d'edició de rúbriques de Moodle.",
      dataThree: "Accions de l'usuari necessàries per realitzar la importació, com seleccionar un fitxer o iniciar-la.",
      dataFour: "Dades tècniques de sol·licitud necessàries per completar crides opcionals a APIs remotes d'IA, si aquestes funcions estan habilitades.",
      useTitle: "Com usa l'extensió les dades",
      useOne: "Per interpretar el contingut CSV/Excel i extreure criteris, nivells i puntuacions.",
      useTwo: "Per inserir la interfície d'importació en pàgines compatibles d'edició de rúbriques de Moodle.",
      useThree: "Per completar el formulari de la rúbrica de Moodle amb les dades proporcionades per l'usuari.",
      useFour: "Per donar suport a funcions opcionals assistides per IA, si existeixen i l'usuari les utilitza.",
      aiTitle: "Processament amb IA",
      aiText: "L'extensió pot incloure funcions assistides per IA en algunes versions. Quan aquestes funcions estiguin disponibles, les dades es podran processar d'una d'aquestes dues maneres, segons la funció i la configuració:",
      aiOne: "Localment al dispositiu de l'usuari mitjançant un model local.",
      aiTwo: "De manera remota a través d'un proveïdor extern d'API d'IA utilitzat per completar la funció sol·licitada.",
      aiProviderText: "Quan s'utilitzi processament remot amb IA, només s'hauria de transmetre el contingut raonablement necessari per executar la funció sol·licitada per l'usuari. Això pot incloure fragments del fitxer CSV/Excel seleccionat, text de la rúbrica a la pàgina de Moodle i prompts o instruccions de l'usuari. Si s'utilitza un proveïdor remot, aquest proveïdor podrà tractar les dades enviades d'acord amb els seus propis termes i política de privacitat.",
      shareTitle: "Compartició de dades",
      shareText: "No venem dades d'usuari. No compartim dades d'usuari amb tercers excepte en aquests casos:",
      shareOne: "Quan l'usuari utilitza explícitament una funció assistida per IA que depèn d'un proveïdor remot d'API.",
      shareTwo: "Quan la divulgació és exigida per llei, regulació o procés legal.",
      shareThree: "Quan compartir la informació és tècnicament necessari per prestar la funció sol·licitada a través de la infraestructura de xarxa.",
      remoteTitle: "Codi remot",
      remoteText: "L'extensió no descarrega ni executa codi remot JavaScript o WebAssembly com a part del seu funcionament principal.",
      retentionTitle: "Conservació de dades",
      retentionText: "L'extensió està dissenyada per processar les importacions localment al navegador sempre que sigui possible. No operem una base de dades backend per emmagatzemar fitxers de rúbriques importats ni contingut de pàgines Moodle. Si s'utilitza una API remota opcional d'IA, les dades transmeses podran ser conservades pel proveïdor corresponent segons la seva pròpia política.",
      securityTitle: "Seguretat",
      securityText: "Procurem minimitzar l'accés a dades a allò estrictament necessari per a la finalitat única de l'extensió. Quan existeixin sol·licituds a APIs remotes, s'haurien de transmetre per canals segurs com HTTPS.",
      choiceTitle: "Opcions de l'usuari",
      choiceOne: "Els usuaris trien quin fitxer CSV/Excel importar.",
      choiceTwo: "Els usuaris poden deixar d'usar l'extensió en qualsevol moment desinstal·lant-la.",
      choiceThree: "Els usuaris poden evitar el processament remot amb IA no utilitzant funcions assistides per IA que depenguin d'APIs externes.",
      changesTitle: "Canvis en aquesta política",
      changesText: "Aquesta Política de Privacitat pot actualitzar-se quan canviï l'extensió, incloent-hi el cas que s'introdueixin noves funcions assistides per IA o noves integracions. L'última versió publicada d'aquesta pàgina és la que resulta aplicable.",
      contactTitle: "Contacte",
      contactText: "Per a consultes de privacitat o suport, utilitza el contacte o l'URL de suport indicada a la fitxa de Chrome Web Store de Rubricando per a Moodle."
    }
  },
  eu: {
    meta: {
      indexTitle: "Rubricando Moodlerako",
      indexDescription: "Rubricando Moodlerako CSV/Excel fitxategietatik Moodleren errubrikak inportatzen dituen luzapena da.",
      privacyTitle: "Pribatutasun Politika | Rubricando Moodlerako",
      privacyDescription: "Rubricando Moodlerako luzapenaren pribatutasun politika."
    },
    language: { label: "Hizkuntza" },
    nav: {
      main: "Nabigazio nagusia",
      homeLabel: "Rubricando Moodlerako hasiera",
      sections: "Orriaren atalak",
      privacyNav: "Pribatutasun nabigazioa",
      workflow: "Fluxua",
      format: "CSV/Excel formatua",
      prompt: "IA prompta",
      install: "Instalazioa",
      privacy: "Pribatutasuna",
      home: "Hasiera"
    },
    footer: {
      privacy: "Pribatutasun politika",
      backHome: "Itzuli azalera"
    },
    index: {
      heroEyebrow: "CSV/Excel inportazioa Moodleren errubrika editorearentzat",
      heroTitle: "Sortu Moodleren errubrikak CSV/Excel batetik, gelaxka bakoitza eskuz bete beharrean.",
      heroText: "Rubricando Moodlerako luzapenak inportazio geruza arin bat gehitzen dio Moodleren errubrika editoreari. Utzi CSV/Excel bat, berrikusi egitura eta utzi luzapenari irizpideak, mailen deskribapenak eta puntuazioak zuzenean erabiltzen duzun orrian betetzen.",
      installCta: "Instalatu Chrome Web Storetik",
      formatCta: "Ikusi CSV/Excel formatua",
      heroPointsLabel: "Abantaila nagusiak",
      pointOne: "Zuzenean funtzionatzen du Moodleren errubrikak editatzeko orrietan",
      pointTwo: "Irizpide bakoitzeko bi errenkada dituzten CSV/Excel fitxategi sinpleak onartzen ditu",
      pointThree: "Luzapena arin mantentzen du CSV parser natibo batekin",
      heroImageAlt: "Rubricandoren inportazio eremua Moodleren errubrika editatzeko orri batean",
      workflowTitle: "Nola funtzionatzen du",
      workflowText: "Bi une nagusi daude: CSV/Excela inportatzea eta Moodleren barruan egituratutako errubrika batekin amaitzea.",
      stepOneTitle: "Utzi CSV/Excela errubrika editorean",
      stepOneText: "Luzapenak inportazio eremu ikusgai bat txertatzen du Moodleren errubrika editorearen URL bateragarrietan; beraz, inportazioa errubrika editatzen ari den leku berean hasten da.",
      stepOneAlt: "CSV/Excel inportazio interfazea Moodleren errubrika editorean txertatuta",
      stepTwoTitle: "Bete irizpideak, mailak eta puntuazioak",
      stepTwoText: "Fitxategia interpretatu ondoren, Rubricandok errubrikaren formularioa osatzen du inportatutako egiturarekin eta baieztapen mezua erakusten du zuzenean orrian.",
      stepTwoAlt: "Moodlera inportatutako errubrikaren edukia arrakasta baieztapenarekin",
      formatTitle: "Nola egituratu behar da CSV/Excela",
      formatText: "Formatua nahita sinplea da. Irizpide bakoitzak bi errenkada hartzen ditu eta eskuinerantz hazten da.",
      rulesTitle: "Arauak",
      ruleOne: "<code>A</code> zutabeak irizpidearen izena dauka.",
      ruleTwo: "Irizpide bakoitzak zehazki bi errenkada erabiltzen ditu.",
      ruleThree: "<code>B</code> zutabetik aurrera mailen deskribapenak lehen errenkadan doaz.",
      ruleFour: "Beheko errenkadak maila bakoitzaren puntuazio zenbakizkoa dauka.",
      ruleFive: "Inportazioa gelditzen da <code>A</code> zutabean irizpide gelaxka huts bat aurkitzen denean.",
      csvTitle: "CSV adibidea",
      csvExample: "Argitasuna,Nahikoa ez,Egokia,Bikaina\n,1,3,5\nArgudiaketa,Ahula,Zuzena,Sendoa\n,2,4,6",
      mapTitle: "Mapa bisuala",
      mapLabel: "CSV egituraren adibidea zutabeen arabera",
      mapCriterion: "Irizpidea",
      mapLevelText: "Maila testua",
      mapPoints: "Puntuak",
      promptTitle: "Sortu errubrikak IArekin formatu egokian",
      promptText: "IA tresna bati eska diezaiokezu errubrika zuzenean Rubricandorekin bateragarria den CSV gisa prestatzeko. Egokitu jarduera, hezkuntza maila, irizpideak eta puntuazioak erabili aurretik.",
      promptCardTitle: "Gomendatutako prompta",
      promptExample: "Jokatu hezkuntza ebaluazioko espezialista gisa.\nSortu errubrika honetarako: [jarduera].\nHezkuntza maila: [maila].\nIrizpide kopurua: [kopurua].\nJardun mailak: [mailen izenak eta puntuazioak].\n\nItzuli soilik CSV baliozkoa, Markdownik gabe, goibururik gabe eta azalpenik gabe.\nNahitaezko formatua:\n- Irizpide bakoitzak bi errenkada erabiltzen ditu.\n- Lehen errenkadan, A zutabea: irizpidearen izena; B zutabetik aurrera: mailen deskribapenak.\n- Bigarren errenkadan, A zutabea hutsik; B zutabetik aurrera: puntuazio zenbakizkoak.\n- Erabili koma bereizle gisa.\n- Testuren batek komak baditu, jarri gelaxka hori komatxo bikoitzen artean.",
      promptNoteTitle: "Inportatu aurretik",
      promptNoteText: "Berrikusi CSVa kalkulu-orri batean inportatu aurretik. Luzapenak bi errenkada espero ditu irizpide bakoitzeko: bat deskribapenekin eta bestea puntuazioekin.",
      featuresTitle: "Zergatik erabiltzen da",
      featuresText: "Foku argiarekin diseinatuta dago: zeregin bakarra, Moodleren fluxuan zuzenean ebatzia.",
      featureOneTitle: "Prestaketa azkarra",
      featureOneText: "Prestatu errubrikaren egitura CSV/Excel batean eta saihestu Moodle barruan maila bakoitza eskuz berreraikitzea.",
      featureTwoTitle: "Aztarna arina",
      featureTwoText: "Ez du hirugarrenen kalkulu-orri liburutegirik sartzen; horrela paketea txikia eta zuzena da.",
      featureThreeTitle: "Interfaze lokalizatua",
      featureThreeText: "Ingelesa, gaztelania, frantsesa, alemana, portugesa, galegoa, katalana eta euskara barne hartzen ditu.",
      installTitle: "Instalatzeko prest",
      installText: "{version} bertsioa Chrome Web Storetik instalatzen da.",
      storeCta: "Ireki Chrome Web Storen"
    },
    privacy: {
      heroTitle: "Pribatutasun Politika",
      heroText: "Pribatutasun Politika honek azaltzen du nola tratatzen dituen Rubricando Moodlerako luzapenak datuak erabiltzaileek Moodleren errubrikak CSV/Excel fitxategietatik inportatzen dituztenean eta, erabilgarri daudenean, IAk lagundutako funtzioak erabiltzen dituztenean.",
      whoTitle: "Nor gara",
      whoText: "Rubricando Moodlerako Chrome luzapen bat da, CSV/Excel fitxategietatik irizpideak, mailen deskribapenak eta puntuazioak Moodleren errubrikak editatzeko orrietara inportatzen laguntzeko diseinatua.",
      dataTitle: "Zer datu tratatzen ditu luzapenak",
      dataIntro: "Luzapenak datu kategoria hauek trata ditzake:",
      dataOne: "Erabiltzaileak berariaz hautatutako edo utzitako CSV/Excel fitxategiak.",
      dataTwo: "Moodleren errubrikak editatzeko orri bateragarrietan lehendik dagoen errubrikekin lotutako edukia.",
      dataThree: "Inportazioa egiteko behar diren erabiltzaile ekintzak, hala nola fitxategi bat hautatzea edo inportazioa hastea.",
      dataFour: "Urruneko IA APIetara aukerako deiak osatzeko behar diren eskaera datu teknikoak, funtzio horiek gaituta badaude.",
      useTitle: "Nola erabiltzen ditu luzapenak datuak",
      useOne: "CSV/Excel edukia interpretatzeko eta irizpideak, mailak eta puntuazioak ateratzeko.",
      useTwo: "Inportazio interfazea Moodleren errubrikak editatzeko orri bateragarrietan txertatzeko.",
      useThree: "Moodleren errubrika formularioa erabiltzaileak emandako datuekin osatzeko.",
      useFour: "IAk lagundutako aukerako funtzioak onartzeko, existitzen badira eta erabiltzaileak erabiltzen baditu.",
      aiTitle: "IA bidezko prozesamendua",
      aiText: "Luzapenak IAk lagundutako funtzioak izan ditzake bertsio batzuetan. Funtzio horiek erabilgarri daudenean, datuak bi modu hauetako batean prozesa daitezke, funtzioaren eta konfigurazioaren arabera:",
      aiOne: "Tokian bertan erabiltzailearen gailuan, eredu lokal baten bidez.",
      aiTwo: "Urrunetik, eskatutako funtzioa osatzeko erabiltzen den kanpoko IA API hornitzaile baten bidez.",
      aiProviderText: "IA bidezko urruneko prozesamendua erabiltzen denean, erabiltzaileak eskatutako funtzioa exekutatzeko arrazoiz beharrezkoa den edukia bakarrik transmititu beharko litzateke. Horrek hautatutako CSV/Excel fitxategiaren zatiak, Moodle orriko errubrika testua eta erabiltzailearen promptak edo jarraibideak har ditzake. Urruneko hornitzaile bat erabiltzen bada, hornitzaile horrek bidalitako datuak bere baldintzen eta pribatutasun politikaren arabera trata ditzake.",
      shareTitle: "Datuen partekatzea",
      shareText: "Ez ditugu erabiltzaile datuak saltzen. Ez ditugu erabiltzaile datuak hirugarrenekin partekatzen kasu hauetan izan ezik:",
      shareOne: "Erabiltzaileak urruneko API hornitzaile baten mende dagoen IAk lagundutako funtzio bat berariaz erabiltzen duenean.",
      shareTwo: "Datuak ezagutaraztea legeak, araudiak edo prozedura legalak eskatzen duenean.",
      shareThree: "Informazioa partekatzea teknikoki beharrezkoa denean eskatutako funtzioa sare azpiegituraren bidez emateko.",
      remoteTitle: "Urruneko kodea",
      remoteText: "Luzapenak ez du urruneko JavaScript edo WebAssembly koderik deskargatzen edo exekutatzen bere funtzionamendu nagusiaren parte gisa.",
      retentionTitle: "Datuen kontserbazioa",
      retentionText: "Luzapena inportazioak ahal den guztietan nabigatzailean lokalki prozesatzeko diseinatuta dago. Ez dugu backend datu-baserik erabiltzen inportatutako errubrika fitxategiak edo Moodle orrien edukia gordetzeko. Urruneko aukerako IA API bat erabiltzen bada, transmititutako datuak dagokion hornitzaileak gorde ditzake bere politikaren arabera.",
      securityTitle: "Segurtasuna",
      securityText: "Datuetarako sarbidea luzapenaren helburu bakarrerako guztiz beharrezkoa denera mugatzen saiatzen gara. Urruneko APIetarako eskaerak daudenean, HTTPS bezalako kanal seguruen bidez transmititu beharko lirateke.",
      choiceTitle: "Erabiltzailearen aukerak",
      choiceOne: "Erabiltzaileek aukeratzen dute zein CSV/Excel fitxategi inportatu.",
      choiceTwo: "Erabiltzaileek edozein unetan utz dezakete luzapena erabiltzeari, desinstalatuz.",
      choiceThree: "Erabiltzaileek IA bidezko urruneko prozesamendua saihestu dezakete kanpoko APIen mende dauden IAk lagundutako funtzioak ez erabiliz.",
      changesTitle: "Politika honen aldaketak",
      changesText: "Pribatutasun Politika hau eguneratu daiteke luzapena aldatzen denean, besteak beste IAk lagundutako funtzio edo integrazio berriak sartzen direnean. Orri honen azken bertsio argitaratua da aplikagarria.",
      contactTitle: "Kontaktua",
      contactText: "Pribatutasun edo laguntza kontsultetarako, erabili Rubricando Moodlerako luzapenaren Chrome Web Store fitxan adierazitako kontaktua edo laguntza URLa."
    }
  }
};

const extensionVersion = getInitialVersion();

function getInitialVersion() {
  const installText = document.querySelector('[data-i18n="index.installText"]')?.textContent || "";
  const versionMatch = installText.match(/(?:versi(?:ó|o)n|version)\s+([0-9.]+)/i);
  return versionMatch?.[1] || "";
}

function getPathValue(source, path) {
  return path.split(".").reduce((current, key) => current?.[key], source);
}

function normalizeLanguage(language) {
  const baseLanguage = String(language || "").toLowerCase().split("-")[0];
  return supportedLanguages.includes(baseLanguage) ? baseLanguage : "es";
}

function getCurrentLanguage() {
  const params = new URLSearchParams(window.location.search);
  const paramLanguage = params.get("lang");
  if (paramLanguage) {
    return normalizeLanguage(paramLanguage);
  }

  const storedLanguage = window.localStorage.getItem("rubricando-language");
  if (storedLanguage) {
    return normalizeLanguage(storedLanguage);
  }

  return normalizeLanguage(navigator.language);
}

function interpolate(text) {
  return String(text).replaceAll("{version}", extensionVersion);
}

function translateNode(node, key, language) {
  const value = getPathValue(translations[language], key) ?? getPathValue(translations.es, key);
  if (typeof value !== "string") {
    return;
  }

  node.innerHTML = interpolate(value);
}

function translateAttributes(node, config, language) {
  for (const pair of config.split(";")) {
    const [attribute, key] = pair.split(":").map((part) => part.trim());
    const value = getPathValue(translations[language], key) ?? getPathValue(translations.es, key);
    if (!attribute || typeof value !== "string") {
      continue;
    }

    node.setAttribute(attribute, interpolate(value));
  }
}

function updateLanguageLinks(language) {
  document.querySelectorAll("a[href]").forEach((link) => {
    const url = new URL(link.getAttribute("href"), window.location.href);
    if (!url.pathname.endsWith(".html")) {
      return;
    }

    url.searchParams.set("lang", language);
    link.setAttribute("href", `${url.pathname.split("/").pop()}${url.search}`);
  });
}

function applyLanguage(language) {
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((node) => translateNode(node, node.dataset.i18n, language));
  document.querySelectorAll("[data-i18n-attr]").forEach((node) => translateAttributes(node, node.dataset.i18nAttr, language));
  document.querySelectorAll("[data-language-select]").forEach((select) => {
    select.value = language;
  });

  const translatedTitle = document.querySelector("title")?.textContent;
  if (translatedTitle) {
    document.title = translatedTitle;
  }

  updateLanguageLinks(language);
  window.localStorage.setItem("rubricando-language", language);
}

function setLanguage(language) {
  const normalizedLanguage = normalizeLanguage(language);
  const params = new URLSearchParams(window.location.search);
  params.set("lang", normalizedLanguage);
  const nextUrl = `${window.location.pathname}?${params.toString()}${window.location.hash}`;
  window.history.replaceState({}, "", nextUrl);
  applyLanguage(normalizedLanguage);
}

document.addEventListener("DOMContentLoaded", () => {
  const language = getCurrentLanguage();
  applyLanguage(language);
  document.querySelectorAll("[data-language-select]").forEach((select) => {
    select.addEventListener("change", () => setLanguage(select.value));
  });
});
